version: "3"
services:

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devfolio
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=development